"""cors2

Revision ID: a7ef1fddafd6
Revises: 4a5ae70b33be
Create Date: 2024-04-09 01:47:27.407079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ef1fddafd6'
down_revision = '4a5ae70b33be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
